name: "Release Action"
on: 
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 3

      - name: Semantic Releasing
        env: # use a non github action token, to allow triggering other workflows (publish)
          GITHUB_TOKEN: ${{ secrets.SEMREL_GH_TOKEN }}
        run: npx semantic-release
